/****************************************************************************** 
 *                      Code generated with sympy 0.6.7                       * 
 *                                                                            * 
 *              See http://www.sympy.org/ for more information.               * 
 *                                                                            * 
 *                       This file is part of 'project'                       * 
 ******************************************************************************/

#ifndef PROJECT__.._C_CODE_SYMPY_INCOMPRESSIBLE_FLOW_SOURCE_QV__H
#define PROJECT__.._C_CODE_SYMPY_INCOMPRESSIBLE_FLOW_SOURCE_QV__H

double U(double a_u0, double a_ux, double a_uxy, double a_uxz, double a_uy, double a_uyz, double a_uz, double b_ux, double b_uxy, double b_uxz, double b_uy, double b_uyz, double b_uz, double c_ux, double c_uxy, double c_uxz, double c_uy, double c_uyz, double c_uz, double d_uxy, double d_uxz, double d_uyz, double e_uxy, double e_uxz, double e_uyz, double f_u0, double f_ux, double f_uxy, double f_uxz, double f_uy, double f_uyz, double f_uz, double g_u0, double g_ux, double g_uxy, double g_uxz, double g_uy, double g_uyz, double g_uz, double t, double twopi_invLx, double twopi_invLy, double twopi_invLz, double x, double y, double z);
double V(double a_v0, double a_vx, double a_vxy, double a_vxz, double a_vy, double a_vyz, double a_vz, double b_vx, double b_vxy, double b_vxz, double b_vy, double b_vyz, double b_vz, double c_vx, double c_vxy, double c_vxz, double c_vy, double c_vyz, double c_vz, double d_vxy, double d_vxz, double d_vyz, double e_vxy, double e_vxz, double e_vyz, double f_v0, double f_vx, double f_vxy, double f_vxz, double f_vy, double f_vyz, double f_vz, double g_v0, double g_vx, double g_vxy, double g_vxz, double g_vy, double g_vyz, double g_vz, double t, double twopi_invLx, double twopi_invLy, double twopi_invLz, double x, double y, double z);
double W(double a_w0, double a_wx, double a_wxy, double a_wxz, double a_wy, double a_wyz, double a_wz, double b_wx, double b_wxy, double b_wxz, double b_wy, double b_wyz, double b_wz, double c_wx, double c_wxy, double c_wxz, double c_wy, double c_wyz, double c_wz, double d_wxy, double d_wxz, double d_wyz, double e_wxy, double e_wxz, double e_wyz, double f_w0, double f_wx, double f_wxy, double f_wxz, double f_wy, double f_wyz, double f_wz, double g_w0, double g_wx, double g_wxy, double g_wxz, double g_wy, double g_wyz, double g_wz, double t, double twopi_invLx, double twopi_invLy, double twopi_invLz, double x, double y, double z);
double Q_v(double Re, double U, double V, double W, double a_ux, double a_uxy, double a_uxz, double a_uy, double a_uyz, double a_uz, double a_vx, double a_vxy, double a_vxz, double a_vy, double a_vyz, double a_vz, double a_wx, double a_wxy, double a_wxz, double a_wy, double a_wyz, double a_wz, double b_ux, double b_uxy, double b_uxz, double b_uy, double b_uyz, double b_uz, double b_vx, double b_vxy, double b_vxz, double b_vy, double b_vyz, double b_vz, double b_wx, double b_wxy, double b_wxz, double b_wy, double b_wyz, double b_wz, double c_ux, double c_uxy, double c_uxz, double c_uy, double c_uyz, double c_uz, double c_vx, double c_vxy, double c_vxz, double c_vy, double c_vyz, double c_vz, double c_wx, double c_wxy, double c_wxz, double c_wy, double c_wyz, double c_wz, double d_uxy, double d_uxz, double d_uyz, double d_vxy, double d_vxz, double d_vyz, double d_wxy, double d_wxz, double d_wyz, double e_uxy, double e_uxz, double e_uyz, double e_vxy, double e_vxz, double e_vyz, double e_wxy, double e_wxz, double e_wyz, double f_ux, double f_uxy, double f_uxz, double f_uy, double f_uyz, double f_uz, double f_vx, double f_vxy, double f_vxz, double f_vy, double f_vyz, double f_vz, double f_wx, double f_wxy, double f_wxz, double f_wy, double f_wyz, double f_wz, double g_ux, double g_uxy, double g_uxz, double g_uy, double g_uyz, double g_uz, double g_vx, double g_vxy, double g_vxz, double g_vy, double g_vyz, double g_vz, double g_wx, double g_wxy, double g_wxz, double g_wy, double g_wyz, double g_wz, double t, double twopi_invLx, double twopi_invLy, double twopi_invLz, double x, double y, double z);

#endif

